name: sos_projeto_ifc_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.6
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.2.2
  permission_handler: ^11.3.1
  flutter_inappwebview: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/Logo_SOS.png"  # coloque sua imagem aqui com esse nome

flutter:
  uses-material-design: true

  assets:
    - assets/icon/Logo_SOS.png
